// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrkDv2YPNISPAACiN466mbAeta4q905wU',
    appId: '1:937502403229:android:762b8780480806570c0274',
    messagingSenderId: '937502403229',
    projectId: 'multivenderapp',
    storageBucket: 'multivenderapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDX_GNcM7wlwEVUJiiGP5BN2xGTEZPhkmQ',
    appId: '1:937502403229:ios:b2eee17ff7c90ab00c0274',
    messagingSenderId: '937502403229',
    projectId: 'multivenderapp',
    storageBucket: 'multivenderapp.firebasestorage.app',
    androidClientId: '937502403229-gkgl0h4biscr6bh2dnhad29a8jc3n9ec.apps.googleusercontent.com',
    iosClientId: '937502403229-q04nvkob9303cdnn7018ucmqujkkh0qt.apps.googleusercontent.com',
    iosBundleId: 'com.marshalfood.app',
  );

}